package models

import (
	"time"
)

// User represents the user model for auth & RBAC
type User struct {
	ID           uint      `gorm:"primaryKey" json:"id"`
	Username     string    `gorm:"uniqueIndex;type:varchar(50);not null" json:"username"`
	PasswordHash string    `gorm:"type:varchar(255);not null" json:"-"`
	Role         string    `gorm:"type:varchar(20);not null" json:"role"` // 'ADMIN', 'PERENCANAAN', 'KEUANGAN', 'MANAJER'
	Name         string    `gorm:"type:varchar(100);not null" json:"name"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

// PRK represents Program Rencana Kerja
type PRK struct {
	ID            uint      `gorm:"primaryKey" json:"id"`
	NomorPRK      string    `gorm:"uniqueIndex;type:varchar(50);not null" json:"nomor_prk"`
	UraianPRK     string    `gorm:"type:text;not null" json:"uraian_prk"`
	JenisAnggaran string    `gorm:"type:varchar(20);not null" json:"jenis_anggaran"` // 'OPERASI' atau 'INVESTASI'
	Tahun         int       `gorm:"not null" json:"tahun"`
	Pagus         []Pagu    `gorm:"foreignKey:PRKID;constraint:OnDelete:CASCADE" json:"pagus"`
	Contracts     []Contract `gorm:"foreignKey:PRKID;constraint:OnDelete:CASCADE" json:"contracts"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

// Pagu represents the budget quota for a PRK
type Pagu struct {
	ID        uint      `gorm:"primaryKey" json:"id"`
	PRKID     uint      `gorm:"not null" json:"prk_id"`
	NilaiPagu float64   `gorm:"type:numeric(15,2);not null" json:"nilai_pagu"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// Contract represents the third-party contracts associated with a PRK
type Contract struct {
	ID             uint      `gorm:"primaryKey" json:"id"`
	PRKID          uint      `gorm:"not null" json:"prk_id"`
	NomorKontrak   string    `gorm:"uniqueIndex;type:varchar(50);not null" json:"nomor_kontrak"`
	JudulPekerjaan string    `gorm:"type:text;not null" json:"judul_pekerjaan"`
	Vendor         string    `gorm:"type:varchar(100);not null" json:"vendor"`
	NilaiKontrak   float64   `gorm:"type:numeric(15,2);not null" json:"nilai_kontrak"`
	StatusProses   string    `gorm:"type:varchar(50);default:'DRAFT'" json:"status_proses"` // 'DRAFT', 'PROSES', 'SELESAI'
	TglND          string    `gorm:"type:varchar(50)" json:"tgl_nd"`
	NoND           string    `gorm:"type:varchar(100)" json:"no_nd"`
	UserBidang     string    `gorm:"type:varchar(50)" json:"user_bidang"`
	HariKerja      int       `gorm:"default:0" json:"hari_kerja"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

// Alert represents critical warnings generated by EWS
type Alert struct {
	ID         uint      `gorm:"primaryKey" json:"id"`
	ContractID *uint     `json:"contract_id,omitempty"`
	PRKID      *uint     `json:"prk_id,omitempty"`
	Tipe       string    `gorm:"type:varchar(50);not null" json:"tipe"` // 'BACKLOG' atau 'BUDGET_CRITICAL'
	Pesan      string    `gorm:"type:text;not null" json:"pesan"`
	CreatedAt  time.Time `json:"created_at"`
}

// Permission represents granular permission codes
type Permission struct {
	Code     string `gorm:"primaryKey;type:varchar(50)" json:"code"`
	Nama     string `gorm:"type:varchar(100);not null" json:"nama"`
	Kategori string `gorm:"type:varchar(50);not null" json:"kategori"`
}

// RolePermission maps user roles to specific permission codes
type RolePermission struct {
	RoleName       string `gorm:"primaryKey;type:varchar(50)" json:"role_name"`
	PermissionCode string `gorm:"primaryKey;type:varchar(50)" json:"permission_code"`
}

// Role represents user role names and descriptions
type Role struct {
	Name      string    `gorm:"primaryKey;type:varchar(50)" json:"name"`
	Deskripsi string    `gorm:"type:varchar(255)" json:"deskripsi"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
